#!/usr/bin/env bash
HOME=/projects/tcamp
PIDFILE=$HOME/data/pidfile
SOCKET=unix:$HOME/data/socket
WORKERS=4
CODEROOT=$HOME/src/current

if [ -f $PIDFILE ]; then
    PID=$(cat $PIDFILE)
    echo "killing process $PID"
    kill $PID
fi

$HOME/virt/bin/python $CODEROOT/manage.py run_gunicorn -b $SOCKET -p $PIDFILE -w $WORKERS --daemon --log-file=$HOME/log/gunicorn.log --preload
