#!/usr/bin/env bash
ROOT=/projects/tcamp
PIDFILE=$ROOT/data/pidfile
SOCKET=unix:$ROOT/data/socket
WORKERS=8
CODEROOT=$ROOT/src/current

if [ -f $PIDFILE ]; then
    PID=$(cat $PIDFILE)
    echo "killing process $PID"
    kill $PID
fi

$ROOT/virt/bin/python $CODEROOT/manage.py run_gunicorn -b $SOCKET -p $PIDFILE -w $WORKERS --log-file=$ROOT/log/gunicorn.log --preload
echo "Running with PID $(cat $PIDFILE)"